In [1]:
import pandas as pd
import numpy as np

In [5]:
from tensorflow.keras import datasets

In [3]:
datasets

<module 'keras.datasets' from '/usr/local/lib/python3.10/dist-packages/keras/datasets/__init__.py'>

In [6]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [7]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [8]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [10]:
x_train.shape

(60000, 28, 28)

In [12]:
width, height = 28, 28
input_shape = (width, height,1)

In [13]:
input_shape

(28, 28, 1)

In [14]:
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)

In [15]:
x_train.shape

(60000, 28, 28, 1)

In [17]:
y_train.shape

(60000,)

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val =  train_test_split(x_train, y_train, test_size = 0.1)

In [19]:
len(x_val)

6000

In [20]:
(x_train) = (x_train - x_train.mean()) / x_train.std()
(x_val) = (x_val - x_val.mean()) / x_val.std()
(x_test) = (x_test - x_test.mean()) / x_test.std()

In [22]:
## all the features will be scaled

In [ ]:
x_train

In [23]:
y_train

array([3, 5, 8, ..., 7, 0, 4], dtype=uint8)

In [24]:
from tensorflow import keras

In [25]:
num_labels = 10
y_train = keras.utils.to_categorical(y_train)

In [26]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [27]:
y_val = keras.utils.to_categorical(y_val)
y_test = keras.utils.to_categorical(y_test)

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input, Conv2D, MaxPooling2D, AveragePooling2D

In [34]:
model = Sequential()
# feature extractor
model.add(Conv2D(6, kernel_size = (5, 5), strides = (1,1),activation ='tanh', input_shape = (28, 28 ,1)))
model.add(AveragePooling2D(pool_size = (2,2), strides = (1,1)))
model.add(Conv2D(16, kernel_size = (5, 5), strides = (1,1),activation ='tanh'))
model.add(AveragePooling2D(pool_size = (2,2), strides = (2,2)))
model.add(Conv2D(120, kernel_size = (5, 5), strides = (1,1),activation ='tanh'))

#converting into single dimension vector
model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels, activation = 'softmax'))

In [36]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d (AverageP  (None, 23, 23, 6)        0         
 ooling2D)                                                       
                                                                 
 conv2d_1 (Conv2D)           (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_1 (Averag  (None, 9, 9, 16)         0         
 ePooling2D)                                                     
                                                                 
 conv2d_2 (Conv2D)           (None, 5, 5, 120)         48120     
                                                                 
 flatten (Flatten)           (None, 3000)              0

In [38]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam', metrics = ['accuracy'])

In [39]:
history = model.fit(x_train, y_train, batch_size = 32, epochs = 5, verbose = 1, validation_data = (x_val,y_val))

Epoch 1/5
1688/1688 [==============================] - 43s 25ms/step - loss: 0.1611 - accuracy: 0.9509 - val_loss: 0.0817 - val_accuracy: 0.9748
Epoch 2/5
1688/1688 [==============================] - 44s 26ms/step - loss: 0.0876 - accuracy: 0.9737 - val_loss: 0.1102 - val_accuracy: 0.9652
Epoch 3/5
1688/1688 [==============================] - 41s 24ms/step - loss: 0.0738 - accuracy: 0.9774 - val_loss: 0.0635 - val_accuracy: 0.9798
Epoch 4/5
1688/1688 [==============================] - 42s 25ms/step - loss: 0.0696 - accuracy: 0.9785 - val_loss: 0.0678 - val_accuracy: 0.9797
Epoch 5/5
1688/1688 [==============================] - 41s 24ms/step - loss: 0.0617 - accuracy: 0.9813 - val_loss: 0.0724 - val_accuracy: 0.9767


In [40]:
score = model.evaluate(x_test, y_test, verbose = 1)

313/313 [==============================] - 3s 8ms/step - loss: 0.0662 - accuracy: 0.9790


In [41]:
score

[0.06623014062643051, 0.9789999723434448]